### ISSUE TITLE
Lowering Mousespeed

### ISSUE THREAD

**Issue by andiweli** [fgsfdsfgs/UE1#10]
I've set the mouse speed to "1" and it is still very fast when rotating the player to aim. 

Can this be lowered anymore?

**Comment by fgsfdsfgs** [comment]
Mouse speed does not affect gamepads, if that's what you're talking about. In `System/Unreal.ini`, under `[NSDLDrv.NSDLClient]` find `ScaleRUV=500.000000`. That's the right stick sensitivity, change it to like `250` or another number to your liking.

**Comment by andiweli** [comment]
Thank you! That worked ☺️

**Comment by fgsfdsfgs** [comment]
I'll look into implementing a sensitivity slider for sticks in the menu later.
