### ISSUE TITLE
[PSV] Brightness does not change

### ISSUE THREAD

**Issue by once13one** [fgsfdsfgs/UE1#2]
Brightness settings from the game and when editing unreal.ini are not applied. There is no effect when changing the parameter.

**Comment by fgsfdsfgs** [comment]
Brightness is actually not implemented in NOpenGLDrv or in NOpenGLESDrv, this is not even Vita specific.

**Comment by fgsfdsfgs** [comment]
This should be fixed now, at least in the GLES2 renderer.
