### ISSUE TITLE
libstdc++-6.dll not found.

### ISSUE THREAD

**Issue by sirbaratusii** [fgsfdsfgs/UE1#6]
![image](https://github.com/user-attachments/assets/4106f660-bbf6-4049-b98c-de21224ccfdd)

I downloaded the automatic build from the Releases tab "unreal-i686-windows-gcc.zip" and extracted it to my install of Unreal (unpatched) but running Unreal.exe gives me this error.

**Comment by fgsfdsfgs** [comment]
Should be fixed now.
Just in case: you really shouldn't use this to casually play Unreal on PC, since the OldUnreal patch has been around for years.
